name: LuckPerms
version: ${pluginVersion}
description: A permissions plugin
author: Luck
website: https://luckperms.net
main: me.lucko.luckperms.bukkit.LPBukkitBootstrap
load: STARTUP

# Mark the plugin as 1.13 compatible to avoid CB having to perform quite as much unnecessary
# remapping when the plugin is loaded. Note that despite what this setting might otherwise imply,
# LP is still compatible with pre-1.13 releases.
api-version: 1.13

# Load LuckPerms before Vault. This means that all plugins that (soft-)depend
# on Vault depend on LuckPerms too.
#
# This fixes issues caused by plugins obtaining the Vault service provider instance
# only once when they initially enable. (if they haven't depended on LP, our registration
# won't be there yet)
loadbefore: [Vault]

# Soft depend on LilyPad for messaging service impl
# Soft depend on ViaVersion for adventure protocol facet
softdepend: [LilyPad-Connect, ViaVersion]

commands:
  luckperms:
    description: Manage permissions
    aliases: [lp, perm, perms, permission, permissions]
